### ISSUE TITLE
Any models which I try produce gibberish output on with cublas

### ISSUE THREAD

**Issue by pradhyumna85** [noneabove1182/koboldcpp-docker#1]
Hi,
My System specs:

CPU Architecture: x86_64
CPU: 48
RAM: 192 GB
GPU: 4 Nvidia T4
Total VRAM: 64 GB
GPU Compute capability: 7.5
OS: Centos 7

Latest Nvidia docker toolkit, drivers

container running using docker compose with gpu **count: all**

Example command: 
```console
python3 koboldcpp.py --model /app/models/llama-2-13b.ggmlv3.q8_0.bin --port 80 --host 0.0.0.0 --stream --threads 7 --usemlock --usecublas --gpulayers 40
```

How ever with "--noblas" flag it works fine. I tried --useclblast but that also doesn't seem to work (gices error related to some .so file not found)

Getting gibberish outputs with all models I have tried. But same models if I run on a windows 10 machine (16 CPU, 32 GB ram, 8GB Nvidia Quadra RTX 4000, compute capability 7.5) using official **Koboldcpp.exe** works fine  with same/similar settings.

Please help.

**Comment by bartowski1182** [comment]
Hey I'm looking into this, I am also suddenly getting garbage output even though it was working when I tested it, I'll get a fix today

**Comment by pradhyumna85** [comment]
Thanks a lot @noneabove1182, let me know when it is fixed.🙂

**Comment by pradhyumna85** [comment]
@noneabove1182, I even tried older 1.36 image and still the same problem.

**Comment by bartowski1182** [comment]
@pradhyumna85 I think I know the issue but have been driving for 3 hours and still have 30 min left 😅 so I'll update you in under an hour

**Comment by bartowski1182** [comment]
I feel like something is wrong with a latest nvidia driver update, I can't get anything to output nicely even going way back in images that were 100% working, still experimenting to try to find a fix

**Comment by bartowski1182** [comment]
@pradhyumna85 I have a build that at least supports clblast but for the life of me I can't figure out cublas and why it isn't working

**Comment by bartowski1182** [comment]
@pradhyumna85 can you try offloading 0 layers and 1 layer?

**Comment by pradhyumna85** [comment]
> @pradhyumna85 I have a build that at least supports clblast but for the life of me I can't figure out cublas and why it isn't working

Okay got it. Great that you were able to get clblast working. But to harness the power of multiple GPUs, we still would need cublas, correct?

**Comment by bartowski1182** [comment]
> > @pradhyumna85 I have a build that at least supports clblast but for the life of me I can't figure out cublas and why it isn't working
> 
> Okay got it. Great that you were able to get clblast working. But to harness the power of multiple GPUs, we still would need cublas, correct?

I believe so yes, but good news thanks to the good people on kobold discord I should be able to fix this very soon! I'll ping you when it's up

**Comment by bartowski1182** [comment]
@pradhyumna85 Fixed! Pull latest and it should work ! Or use 1.38-fixed/latest from docker hub :D thanks for reporting the issue!

**Comment by bartowski1182** [comment]
fixed in https://github.com/noneabove1182/koboldcpp-docker/commit/331326a0e340ac845855d346f730356b000650c7
