### ISSUE TITLE
Remove space in dockerhub docu

### ISSUE THREAD

**Issue by freehuntx** [noneabove1182/koboldcpp-docker#3]
In the dockerhub documentation at https://hub.docker.com/r/noneabove1182/koboldcpp-gpu you are 1 space too much which causes an invalid yaml.

```
               count: 1
               capabilities: [gpu]
```
should be
```
              count: 1
              capabilities: [gpu]
```

**Comment by bartowski1182** [comment]
Whoops, thanks, fixed it !
