### ISSUE TITLE
Error trying to build

### ISSUE THREAD

**Issue by maethu1337** [noneabove1182/koboldcpp-docker#5]
Hi there. Thanks a lot for your work!

I am trying to build on a Ubuntu 23.04 machine, but I run in the folling error when building. Any ideas? Thanks!

Errors were encountered while processing:
 /tmp/apt-dpkg-install-nadv7m/16-libnvidia-extra-535_535.129.03-0ubuntu1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update && apt-get upgrade -y     && apt-get -y install python3     ocl-icd-opencl-dev opencl-headers clinfo     libclblast-dev libopenblas-dev     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100

**Comment by bartowski1182** [comment]
Hmm that's a curious one. To confirm, you didn't change the base image to 23.04, it's your host machine that's on 23.04? 

Do you have any issues running the prebuilt images? Just to narrow down the problem

I do see some threads of people running into issues with 535 on 23.04 so I'm going to try some of the fixes and see if they work to install on mine at least and then give them to you to try

**Comment by maethu1337** [comment]
> You didn't change the base image to 23.04, it's your host machine that's on 23.04?

Yes, exactly.

> Do you have any issues running the prebuilt images?

The machine I wanted to deploy your current docker version to, gave me:

> Warning, GUI failed to start: Reason: No module named 'tkinter'
> File selection GUI unsupported.
> customtkinter python module required!

So  I thought I could maybe change something in the Dockerfile, but then I even ran into an issue building an unchanged version. 
I think I will try on a 22.04 instance!

Edit: I tried again on a completely fresh 22.04 install. Just:

> apt-get install docker.io
> git clone https://github.com/noneabove1182/koboldcpp-docker.git
> docker build . -t koboldcpp-docker:latest

> Errors were encountered while processing:
>  /tmp/apt-dpkg-install-LZpx09/16-libnvidia-extra-535_535.129.03-0ubuntu1_amd64.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> The command '/bin/sh -c apt-get update && apt-get upgrade -y     && apt-get -y install python3     ocl-icd-opencl-dev opencl-headers clinfo     libclblast-dev libopenblas-dev     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 100

Could it somehow be a problem that I use the root user to build?

**Comment by bartowski1182** [comment]
Okay try the latest that I pushed, I may have forgotten to update the Dockerfile for what I'm currently using

Regarding the tkinter, are you passing a model to load at runtime? if not it may be trying to launch the GUI which I don't think works in docker, but actually I've never tested it so if it does that would be handy to include for people who aren't like me and don't run it on a headless machine

**Comment by maethu1337** [comment]
The Dockerfile is now building, so that has fixed it!

For the other question, I have to run it on a machine where I have ssh access. I tried it on a service, where everything has to be perfect for it to function, and I do not know enough about koboldcpp yet I am afraid. I will create a new issue if needed in the future. Thanks for the support :)
